env = Environment(CC = "gcc",
	CCFLAGS=["-Wall", "-g", "-lm", "-lncurses", "-lSDL2"],
	LIBS=["m", "ncurses", "SDL2"])
env.Program("visualize", ["visualizer.o", "visualizer/window.o", "visualizer/init_audio.o", "input/keyboard.o", "engine/waveforms.o"])
