/**
 * A simple visualizer for sound waves generated by the synthesizer.
 */

#include <SDL2/SDL.h>
#include "visualizer/init_audio.h"
#include "visualizer/window.h"

int main(void) {
    init_window();
    init_audio();
    end_window();
    return EXIT_SUCCESS;
}
