/**
 * A simple visualizer for sound waves generated by the synthesizer.
 */

#include <SDL2/SDL.h>
#include <stdbool.h>
#include "../headers/audio_window.h"
#include "../headers/window.h"
#include "../headers/event.h"

/*
int main(void) {
    init_audio();
    init_window();
    bool keep_running = true;
    SDL_Event event;
    while (keep_running) {
        SDL_RaiseWindow(get_audio_window());
        while (SDL_PollEvent(&event)) {
            if (!handle_event(event)) {
                keep_running = false;
                break;
            }
        }
    }
    end_window();
    return EXIT_SUCCESS;
}
*/